name: create release

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Prepare release
        run: |
          base_tag=v$(npx -c 'echo "$npm_package_version"')
          git checkout -b release $base_tag
          git push origin release
          git merge --no-edit ${{ github.ref }}
          yarn install
      - name: Run release
        run: |
          yarn release
          echo "new_tag=$(git describe)" >> $GITHUB_ENV
      - name: Craete Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'chore(release): ${{ env.new_tag }}'
          base: 'remotes/origin/release'

