name: automatic release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: run release
        run: |
          git checkout -b release-working
          yarn install
          yarn release
          tag=$(git describe)
          git push origin $tag
          git checkout -b merge-release master
          git cherry-pick $tag
      - name: Create PR
        uses: peter-evans/create-pull-request@v3

