name: automatic release

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Prepare release
        run: |
          baseTag=v$(npx -c 'echo "$npm_package_version"')
          git checkout $baseTag
          git merge --no-ff --no-edit master
      - name: Run release
        run: |
          yarn install
          yarn release
      - name: Push release
        run: |
          newTag=$(git describe)
          git push origin $newTag
          git checkout master
          git cherry-pick $newTag
      - uses: peter-evans/create-pull-request@v3

